[package]
name = "deku"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "deku"
path = "src/main.rs"

[dependencies]
deku-core = { path = "../deku-core" }
clap = { workspace = true }
cliclack = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
